# Generated by Django 5.1.1 on 2024-10-06 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='finished',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='value',
        ),
        migrations.AddField(
            model_name='lesson',
            name='color',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
