# Generated by Django 5.1.1 on 2024-10-06 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_lesson_finished_remove_lesson_value_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lesson',
            old_name='img_link',
            new_name='youtube_link',
        ),
    ]
