# Generated by Django 5.1.1 on 2024-10-09 04:37

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_userlesson_profile_delete_report'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userlesson',
            unique_together={('user', 'lesson')},
        ),
    ]
