# Generated by Django 5.1.1 on 2024-10-13 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_userlesson_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='color',
        ),
        migrations.AddField(
            model_name='lesson',
            name='transcript',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='completed_exercises',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='done_rate',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='high_outcome',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='hours_learn_weekly',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='mistakes_count',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
